search-paths:
  -
    kinds: bazel
    path-patterns:
      - "bazel/BUILD.bazel"
post-update-hooks:
  - commands: "buildifier --lint=fix -r ."
    files-to-commit:
      - "bazel/BUILD.bazel"
    run-for: pull-request
    commit-message: "Apply buildifier"
