// Copyright 2025 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include "absl/types/span.h"

#include "libspu/core/value.h"

namespace spu {
class SPUContext;
}

namespace spu::kernel::hal {

// Cuckoo hash based secure join for two unsorted tables, when:
// 1. join keys are unique
// 2. table_1 and table_2 are secret shared

// We take an example of join_uu to illustrate the main steps of the algorithm:
//     table_1={{2,3,1,7,4},{a,b,c,d,e}}, table_2={{3,1,4,8},{f,g,h,i}}
//     num_join_keys=1, num_hash=2, scale_factor=1.5
//     result: {
//   {0, 1, 1, 0, 1}, {2, 3, 1, 7, 4}, {a, b, c, d, e}, {
//     0, f, g, 0, h
//   }
// }

// Steps:
// 1. Compute SoPrf output of join keys, e_1 and e_2, based on the join keys
//    of table_1 and table_2 respectively.
//    e_1={22,33,11,77,44} and e_2={33,11,44,88}.

// 2. Compute cuckoo_hash_size=7.

// 3. Compute perm_all based on e_1 and e_2, where perm_all={perm_1, perm_2,
//    perm_3} (perm_1 and perm_2 are generated by e_1 and perm_3 is generated by
//    e_2 based on Cuckoo Hash).
//    perm_1={0,1,2,6,3,4,5}, perm_2={1,6,4,0,2,3,5} and perm_3={3,0,4,2,1,5,6}.

// 4. table_2_expand={
//     {3,1,4,8,null,null,null},
//     {f,g,h,i,null,null,null},
//     {1,1,1,1,0,0,0}
//     }.

// 5. Perform permutation pi_2 (perm_3 in the example) on table_2_expand to
//    get tbl2_perm_by_pi2.
//    tbl2_perm_by_pi2={
//     {8,3,null,4,1,null,null},
//     {i,f,null,h,g,null,null},
//     {1,1,0,1,1,0,0}
//     }.

// 6. Get each pi_1 (perm_1 and perm_2 in the example) corresponding to each
// hash function, and use it to permute tbl2_perm_by_pi2 to get
// tbl2_perm_by_pi1.
//     tbl2_perm_by_pi1={
//       {8,3,null,null,4},
//       {i,f,null,null,h},
//       {1,1,0,0,1},
//       {3,null,1,8,null},
//       {f,null,g,i,null},
//       {1,0,1,1,0}
//     }.

// 7. tbl2_flag_of_hashes={{0,1,0,0,1},{0,0,1,0,0}}.

// 8.
// table_2_result={tbl2_perm_by_pi1[1]*tbl2_flag_of_hashes[0]+tbl2_perm_by_pi1[4]*tbl2_flag_of_hashes[1]}
// ={{0,f,0,0,h}+{0,0,g,0,0}}={0,f,g,0,h}.

// 9. valid_flag={0,1,0,0,1} or {0,0,1,0,0}={0,1,1,0,1}.

// 10. join_result={
//       {0, 1, 1, 0, 1},
//       {2, 3, 1, 7, 4},
//       {a, b, c, d, e},
//       {0, f, g, 0, h}
//     }.
std::vector<spu::Value> join_uu_ss(SPUContext* ctx,
                                   absl::Span<const spu::Value> table_1,
                                   absl::Span<const spu::Value> table_2,
                                   size_t num_join_keys, size_t num_hash,
                                   double scale_factor);

std::vector<spu::Value> join_uu_vv(SPUContext* ctx,
                                   absl::Span<const spu::Value> table_1,
                                   absl::Span<const spu::Value> table_2,
                                   size_t num_join_keys, size_t num_hash,
                                   double scale_factor);

// Sort-based secure join for two unsorted tables, when:
// 1. join keys in table_1 are unique, while those in table_2 can be duplicate
// 2. table_1 and table_2 are secret shared
//
// We take an example of join_un to illustrate the main steps of the algorithm:
//     table_1={{2,3,1,4},{a,b,c,d}}, table_2={{3,1,4,5,4},{e,f,g,h,i}}
//     num_join_keys=1
//     result: {
//       {1,1,1,0,1},
//       {3,1,4,5,4},
//       {e,f,g,h,i},
//       {b,c,d,0,d}
//     }

// Steps:

// 1. Map the concatenated join keys from table_1 and table_2 to a new vector
// mapped_join_keys of length n_1 + n_2, where n_1 and n_2 are the number of
// rows in table_1 and table_2 respectively. The mapping should satisfy that the
// same join keys are mapped to the same value, and different join keys are
// mapped to different values. mapped_join_keys={22,33,11,44,33,11,44,55,44}.

// 2. Concatenate mapped_join_keys, and the first n_1 values of mapped_join_keys
// to get mapped_join_keys_concat={22,33,11,44,33,11,44,55,44,22,33,11,44}.

// 3. Sort mapped_join_keys_concat to get permutation
// perm={2,5,11,0,9,1,4,10,3,6,8,12,7}.

// 4. table_1_payloads_and_1={{a,b,c,d},{1,1,1,1}}.

// 5.
// table_1_payloads_processed={{a,b,c,d,0,0,0,0,0,-a,-b,-c,-d},{1,1,1,1,0,0,0,0,0,-1,-1,-1,-1}}.

// 6. Permute table_1_payloads_processed with the inverse of perm to get
// table_1_payloads_after_perm={{a,0,-a,b,0,-b,c,0,-c,d,0,-d,0},{1,0,-1,1,0,-1,1,0,-1,1,0,-1,0}}.

// 7. Perform cumulative sum on table_1_payloads_after_perm to get
// table_1_payloads_after_scan={{a,a,0,b,0,0,c,0,0,d,0,0,0},{1,1,0,1,0,0,1,0,0,1,0,0,0}}.

// 8. Permute table_1_payloads_after_scan with the perm to get
// table_1_payloads_after_inv_perm={{a,a,c,d,b,c,d,0,d,0,b,0,0},{1,1,1,1,1,1,1,0,1,0,1,0,0}}.

// 9. table_1_payloads_result={{b,c,d,0,d},{1,1,1,0,1}}.

// 10. join_result={{1,1,1,0,1},{3,1,4,5,4},{e,f,g,h,i},{b,c,d,0,d}}.
std::vector<spu::Value> join_un(SPUContext* ctx,
                                absl::Span<const spu::Value> table_1,
                                absl::Span<const spu::Value> table_2,
                                size_t num_join_keys);

}  // namespace spu::kernel::hal