# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: examples/python/utils/distributed.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'examples/python/utils/distributed.proto\x12!examples.python.utils.distributed\"\x1a\n\nRunRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1b\n\x0bRunResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xeb\x01\n\x0bNodeService\x12j\n\x03Run\x12-.examples.python.utils.distributed.RunRequest\x1a..examples.python.utils.distributed.RunResponse\"\x00(\x01\x30\x01\x12p\n\tRunReturn\x12-.examples.python.utils.distributed.RunRequest\x1a..examples.python.utils.distributed.RunResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'examples.python.utils.distributed_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RUNREQUEST']._serialized_start=78
  _globals['_RUNREQUEST']._serialized_end=104
  _globals['_RUNRESPONSE']._serialized_start=106
  _globals['_RUNRESPONSE']._serialized_end=133
  _globals['_NODESERVICE']._serialized_start=136
  _globals['_NODESERVICE']._serialized_end=371
# @@protoc_insertion_point(module_scope)
