---
name: CLA Assistant
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
jobs:
  CLAssistant:
    uses: secretflow/.github/.github/workflows/cla.yml@main
    secrets: inherit
